### ISSUE TITLE
Install Instructions?

### ISSUE THREAD

**Issue by DroWnThePoor** [freedosproject/toycpu#1]
Hi, given that this is a tool for someone to learn how to code shouldn't it have an installation guide in the README?

I'm attempting to run/install it on Linux, and I don't know where to even start. I see there is a makefile so I'm guessing I need to run that.

Any help appreciated.

**Comment by freedosproject** [comment]
You mention Linux, so I assume you're trying to compile and run Version 2 of the Toy CPU. Here's what you need:

Before you try to compile, you'll need the ncurses libraries installed on your system. For example, on a Fedora Linux system, type `sudo dnf install ncurses-devel` to install these.

Then do this:

1. Download the toycpu-2.0.tar.gz source archive
2. Extract the archive with `tar xzf toycpu-2.0.tar.gz`
3. go into the source directory with `cd toycpu-2.0`
4. Type `make`

That will compile the Toy CPU so you can run it:

```
$ make
gcc -DUSE_HELP -Wall -c toy.c
gcc -DUSE_HELP -Wall -c screen.c
gcc -DUSE_HELP -Wall -c cpu.c
gcc -DUSE_HELP -Wall -c input.c
gcc -DUSE_HELP -Wall -o toy toy.o screen.o cpu.o input.o -lncurses 
```

and:

```
$ ls
bit.h  cpuinstr.h  input.h  Makefile   screen.h  toy.c
cpu.c  cpu.o       input.o  README.md  screen.o  toy.o
cpu.h  input.c     LICENSE  screen.c   toy
```

Now you can run the Toy CPU by typing `./toy`

**Comment by freedosproject** [comment]
If you're trying to run the Version 3 of the Toy CPU, note that this is a DOS program, so you need to run it under DOS. I use FreeDOS in a virtual machine on Linux, but you can use DOSBox if you prefer.

There's already a DOS executable (EXE) available to download.

If you want to compile this yourself, you'll need the OpenWatcom C compiler. If you're using FreeDOS, you can install this from the FreeDOS LiveCD by running `FDIMPLES` and selecting the OpenWatcom C compiler.

Set up your DOS environment with OpenWatcom C using the `OWSETENV.BAT` batch file, then do this:

1. Download the toycpu-3.0.zip source archive
2. Copy the zip file to your FreeDOS instance (I might save it as `TOYCPU.ZIP` so you can stay within the 8.3 filenames)
3. Extract the archive with `unzip -j toycpu.zip -d toycpu` (the `-j` option says to "junk" the paths, and `-d` says to extract to the `toycpu` directory)
4. Go into the source directory with `cd toycpu`
5. Run the `build.bat` batch file

That should compile it for you. (Key step is to make sure to set up your OpenWatcom C environment first.)

**Comment by freedosproject** [comment]
I'll add some instructions to an `INSTALL.TXT` file, so others know how to compile it.
