### ISSUE TITLE
floppy disk image?

### ISSUE THREAD

**Issue by carloocchiena** [freedosproject/toycpu#2]
That's a great project and I'm gladly sharing it. 

Would make sense to create a floppy disk image (.img) in order to make the experience more "vintage", and, also, make it runnable from online FreeDos emulator?

**Comment by freedosproject** [comment]
If you're asking if the Toy CPU can be put on a disk image so you can run it anywhere: yes, definitely. You could even customize the AUTOEXEC.BAT (or FDAUTO.BAT on FreeDOS) to run the Toy CPU at boot-time, so you can start right away. (If you modify the source code to remove the `Q` to quit, then you could replace the SHELL=COMMAND.COM line with SHELL=TOY.EXE so DOS runs the Toy CPU as the "command shell.")

There's nothing specific to the Toy in doing any of this. Feel free to try it out!

**Comment by freedosproject** [comment]
closed (question, not a bug)
